# Numpy


Intro: Numpy stands for numerical Python, a package used for scientific computation used not just for AI/ML/DS but other areas such as physics, computer graphics. It contains containers such as Lists,Dictionaries inbuilt which makes computation easier.Numpy provides extension package to Python for multi-dimensional array. It is also known as array oriented computing. It is fast and memory efficient.

### Creating Numpy array

In [3]:
import numpy as np
a=np.array([0,1,3,4])#creating narray, we are using np here in order to use elements of numpy pacakge
a

array([0, 1, 3, 4])

In [4]:
b=[1,2,3,5]
a=np.array(b)
a

array([1, 2, 3, 5])

In [5]:
a=np.array(range(10)) # print 10 elements from 0 to 9(n-1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a=np.array(range(0,10,1)) #start:end:step_size
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a=np.array(range(10,1,-1))
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [8]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
print(np.arange(0,10,1))

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(np.arange(10,1,-1)) #start:end:step_size

[10  9  8  7  6  5  4  3  2]


Range gives you a regular list or a specialized "range object" 
np.arange gives you a numpy array. If you care about speed enough to use numpy, use numpy arrays.

In [11]:
a.ndim #dimension of array a,since it is a 1D array, it has dimension 1

1

In [12]:
a.shape #gives row,column

(10,)

In [13]:
len(a)

10

In [14]:
a.size

10

In [15]:
b=np.array([[2,3,5],[2,5,7]])
b

array([[2, 3, 5],
       [2, 5, 7]])

In [16]:
b.ndim

2

In [17]:
b.shape

(2, 3)

In [18]:
b.size #returns the total number of elements in the lists

6

In [19]:
len(b) #returns the number of rows

2

In [20]:
c=np.array([
    [[1,2],[3,4]],[[2,4],[4,5]]
            ])
c

array([[[1, 2],
        [3, 4]],

       [[2, 4],
        [4, 5]]])

In [21]:
c.ndim

3

In [22]:
len(c)

2

In [23]:
c.shape

(2, 2, 2)

In [24]:
c.size

8

In [25]:
#using linspace(linear space):
a=np.linspace(0,2,7)#start:end:no_of_points
a

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        ])

In [26]:
#using ones
a=np.ones((2,3)) #creates 2 rows and 3 column array where all the elements are equal to 1,by default they are floating points intergers
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
#using zeros
a=np.zeros((2,3))#creates specified sized array with all the elements to be zeros 
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
#using eye
a=np.eye(4) #returns a 2D array with ones on the diagonal and zeros elsewhere(identity matrix)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
print(np.eye(3,4)) #3 rows,4columns 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [30]:
#using diagonal
a=np.diag([1,2,3])#creates a diagonal matrix having 1,2,3 in the diagonal
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [31]:
np.diag(a) #extracts diagonal elements of array a

array([1, 2, 3])

In [32]:
#create array using random
a=np.random.rand(4) #returns array of size 4.an array of given shape and populate it with random samples.
a

array([0.87514142, 0.38519307, 0.82854063, 0.93437045])

In [33]:
a=np.random.randint(4)
a

1

In [34]:
a=np.random.rand(4)
a

array([0.57001447, 0.91992582, 0.22106583, 0.33605656])

In [35]:
a=np.random.randint(8)
a

4

### Basic Data Type:

In [36]:
a=np.arange(5)
type(a)

numpy.ndarray

In [37]:
a.dtype

dtype('int32')

In [38]:
a=np.arange(10,dtype='int64') # you can explicitly define which data type you want 
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [39]:
a=np.array([2+1j,1+2j]) #complex data type
a.dtype

dtype('complex128')

In [40]:
b=np.array([True,False,True])
b.dtype

dtype('bool')

In [41]:
c=np.array(["M","A","N","I","S"])
c
c.dtype 

dtype('<U1')

< represents byte order, small end （ the least significant byte is stored in the smallest address ）

U unicode, data type

1 represents element bit length, data size

In [42]:
c=np.array(["Manisha","Bhandari"])
c

array(['Manisha', 'Bhandari'], dtype='<U8')

### Indexing and Slicing

In [43]:
a=np.array([1,3,4,5])
a[3]

5

In [44]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a[2]

2

In [46]:
a=np.diag([2,3])
a

array([[2, 0],
       [0, 3]])

In [47]:
a[1,1] #extract value of row 1 at index 1

3

In [48]:
a[0,1]=5 #reassigning value at specified index
a

array([[2, 5],
       [0, 3]])

In [49]:
a=np.array(range(60))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [50]:
a[2:30:2] #goes from index 2 to index 29 stepping size 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [51]:
a[:] #takes all the elements from the row

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [52]:
a[:5] #takes elements from 0 to 4

array([0, 1, 2, 3, 4])

In [53]:
a[5:] #takes all the elements from 5th index to last

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59])

In [54]:
a[-4:]

array([56, 57, 58, 59])

In [55]:
a[-10:2:-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3])

### Fancy Indexing

Numpy arrays can be indexed with slices but also with boolean or integer arrays(masks).It creats copies not views. It means passing an array of indices to access multiple array elements at once.

In [60]:
a=np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [62]:
even_numbers=a%2==0
a[even_numbers]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [64]:
print(a[a%2!=0]) # here a%2!=0 returns a boolean value based on the condition and outside 'a' extracts elements from the lists 
#which satifies the condition


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [65]:
a%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False])

### Numerical operations on Numpy

In [70]:
## Basic operations with scalars.
a=np.array([4,9,0,1])
a+2 # 2 is added to every element in the numpy array a.

array([ 6, 11,  2,  3])

In [73]:
a=[4,9,0,1]
a+2

TypeError: can only concatenate list (not "int") to list

Here you can see we can't add to the normal list but can easily perform on Numpy. This is why Numpy is preferred more over list.All arithmetic operates element wise in Numpy

In [79]:
b=np.linspace(1,5,4)
b

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [80]:
a-b

array([ 3.        ,  6.66666667, -3.66666667, -4.        ])

In [81]:
a+b

array([ 5.        , 11.33333333,  3.66666667,  6.        ])

In [82]:
a/b

array([4.        , 3.85714286, 0.        , 0.2       ])

In [83]:
a*b

array([ 4., 21.,  0.,  5.])

In [76]:
b=np.linspace(1,5,9)
b

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [78]:
a-b

ValueError: operands could not be broadcast together with shapes (4,) (9,) 

Here, in the example above, we  have error stating'operands could not be broadcast together with shapes (4,) (9,)'. It is because An arithmetic operation between any two arrays is always performed element-by-element. That is if you add two arrays, A and B, every ith element of A is added to the ith element of B to produce the array C. Everything works fine if both the arrays have the same shape. If the arrays have different shapes, then the element-by-element operation is not possible. But, in real-world applications, you will rarely come across arrays that have the same shape. So Numpy also provides the ability to do arithmetic operations on arrays with different shapes. That ability is called <b>broadcasting.</b>
reference:https://www.pluralsight.com/guides/broadcasting-numpy-arrays-arithmeetic-operations

In [84]:
#Matrix Multiplication
c=np.diag([1,3,5,7])
print(c*c)

[[ 1  0  0  0]
 [ 0  9  0  0]
 [ 0  0 25  0]
 [ 0  0  0 49]]


In [85]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  9  0  0]
 [ 0  0 25  0]
 [ 0  0  0 49]]


In [88]:
#comparisions
a=np.array([4,0,8,1])
b=np.array([1,6,1,1])
a==b

array([False, False, False,  True])

In [89]:
#array-wise comparisons
a=np.array([1,4,1])
b=np.array([2,4,1])
np.array_equal(a,b)

False

In [90]:
#Logical Operations
a=np.array([1,0,1],dtype=bool)
b=np.array([0,0,1],dtype=bool)
np.logical_or(a,b) # here 1 represents True and 0 represents False. Logical OR will return boolean value True if any one of the
#value is True otherwise False.

array([ True, False,  True])

In [92]:
np.logical_and(a,b) #Here Logical And will return True if all the elements are true.

array([False, False,  True])

In [93]:
#Transcendental Functions:
a=np.arange(5)
np.sin(a) #computes sin of all elements.


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [95]:
np.log(a)

<ipython-input-95-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [96]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [97]:
#Basic Reductions
x=np.array([1,9,0])
np.sum(x)

10

In [98]:
#sum by rows and columns
x=np.array([[1,2],[4,2]])
x

array([[1, 2],
       [4, 2]])

In [99]:
x.sum(axis=0) #columnwise sum

array([5, 4])

In [101]:
x.sum(axis=1) #rowwise sum

array([3, 6])

In [103]:
x=np.array([3,5,7,1])
x.max()


7

In [104]:
x.min()

1

In [105]:
x.argmax() #returns index of maximum element

2

In [106]:
x.argmin() #returns index of minimum element from the list x

3

In [107]:
#Logical Operations
np.all([True,False,True])

False

In [110]:
a=np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [111]:
np.all(a==0)

True

In [112]:
np.any(a==0)

True

In [113]:
np.any(a!=0)

False

In [114]:
#statistics
x=np.array([1,3,5])
y=np.array([2,9,0])
x.mean()

3.0

In [115]:
np.median(x)

3.0

In [116]:
y.std()

3.8586123009300755